"""add owner age

Revision ID: 778ccb86eb20
Revises: 791094dbd6aa
Create Date: 2021-12-27 17:32:49.310893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778ccb86eb20'
down_revision = '791094dbd6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'age')
    # ### end Alembic commands ###
